server:
  port: 8006

spring:
  application:
    name: cloud-payment-service
  cloud:
    consul:
      # Consul 服务器地址
      host: 192.168.1.14
      port: 8500
      # 服务发现相关配置
      discovery:
        register: true                                # 是否需要注册
        service-name: ${spring.application.name}      # 服务名称
        prefer-ip-address: true                       # 是否使用 ip 地址注册
