server:
  port: 8802
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #绑定的mq的服务信息（这里使用的是rabbitmq）
        test: #Binder定义的名称，用于后面的关联
          type: rabbit # mq的类型，rabbit和 Kafka
          environment: # mq 的环境
            spring:
              rabbitmq:
                addresses: 192.168.7.189
                port: 5672
                username: root
                password: root
                virtual-host: /
      bindings: # 关联整合通道和Binder对象
        input: # 定义的通道名称，
          destination: testRabbit # exchange 的名称
          content-type: application/json #消息的类型
          default-binder: test # 关联的mq服务
          group: testA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳时间，默认30秒
    lease-expiration-duration-in-seconds: 5 #超过5秒，默认90秒
    instance-id: receive-8802.com
    prefer-ip-address: true #访问的路径变为IP地址
