server:
  port: 9999

spring:
  application:
    name: sentinel-service-8041
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #naocs地址
    sentinel:
      transport:
        dashboard: localhost:8080    #sentinel地址
        port: 8719 #端口配置会在应用对应的机器上启动一个Http Server，该Server会与Sentinel控制台做交互。默认8719，被占用会从8719开始依次+1扫描，直到终点未被使用端口。

#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"